services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    container_name: cw_postgres
    networks:
      - chatwoot
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - cw_postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - "CMD"
        - "pg_isready -U postgres"
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 10s


volumes:
  cw_postgres:
    external: true

networks:
  chatwoot:
    external: true